- name: Install and start Apache Http on Amazon Linux 
  hosts: servers1
  become: yes 

  tasks:
  - name: Ensure Apache is Installed
    yum:
      name: httpd
      state: present

  - name: Apache Service is started and enabled  
    service:
      name: httpd
      state: started
      enabled: yes

  - name: Deploy Simple index.html page
    copy:
      dest: /var/www/html/index.html
      content:
        <!DOCTYPE html>
        <html>
        <head>
        <title>welcome</title>
        </head>
        <body>

        <h1>Apache is running on Amazon Linux 
        <p1>managed by Chirayu Shingnapurkar 

        </body>
        </html>

  - name: install firewalld 
    yum:
      name: firewalld
      state: present
      
  - name: start and enable firewalld
    service:
      name: firewalld
      state: started
      enabled: yes






